languageCode = "en-uk"
title = "Teddy's Picnic"
baseurl = "/"
theme = "ezhil"
paginate = 5

copyright = "© Teddy Groves 2021"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = ""

summaryLength = 20

[params]
subtitle = ""
disableDisqusTypes = ["page"]
featherIconsCDN = true
mode = "auto" # "dark", "auto", "light"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About me"
url = "/about"
weight = 3

[[menu.main]]
name = "Data Analysis on Ice"
url = "/data_analysis_on_ice"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/teddygroves"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
